### ISSUE TITLE
Project name collision

### ISSUE THREAD

**Issue by notsponsible** [twitter/sqrl#93]
SQRL (Secure Quick Reliable Login) is the name of a secure login protocol that has been in active development by Steve Gibson of GRC.com since at least October 2013.  

More info here: 
October 2013 Announcement: https://www.grc.com/sn/sn-424.htm
Protocol Documentation: https://www.grc.com/sqrl/sqrl.htm

**Comment by willnorris** [comment]
Hey, thanks for the note!  I absolutely see where you're coming from, and we'll update the project README shortly to try and avoid the confusion.
