### ISSUE TITLE
Error in Installing SQRL - Ubuntu 18

### ISSUE THREAD

**Issue by hari-en** [twitter/sqrl#97]
One line summary of the issue here.

When installing SQRL in ubuntu, The install is failing with the below issue.

gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-1051-aws

### Actual behavior

While installing, am getting the below exception

bignum.target.mk:111: recipe for target 'Release/obj.target/bignum/bignum.o' failed
make: *** [Release/obj.target/bignum/bignum.o] Error 1
make: Leaving directory '/home/ubuntu/node_modules/bignum/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-1051-aws
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/node_modules/bignum
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/package.json'
npm WARN ubuntu No description
npm WARN ubuntu No repository field.
npm WARN ubuntu No README data
npm WARN ubuntu No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bignum@0.13.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-11-07T09_51_51_885Z-debug.log
ubuntu@ip-172-31-12-52:~$ node -v
v12.13.0

### Steps to reproduce the behavior

Please list all relevant steps to reproduce the observed behavior.

Ubuntu 18 

After installing nodeJS v12.13 , executed the below command.
sudo npm install -g sqrl-cli

**Comment by hari-en** [comment]
[error.log](https://github.com/twitter/sqrl/files/3823694/error.log)

Attaching the NPM Debug logs for reference

**Comment by mseshachalam** [comment]
It failed to install using v12 and v13 on ubuntu 18.04 but succeed using v10 of node

**Comment by qix** [comment]
This has been resolved for some time, apologies for forgetting to update the ticket.
